pages:
  stage: deploy
  script:
  - export START_PAGE_USER
  - export $START_PAGE_ID
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master